name: Add GitHub Release Tag

on: [push]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: 0 # Fetch all tags

      - name: Create Release for Tag
        id: release_tag
        uses: Akryum/release-tag@conventional
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_SPONSORED: true
        with:
          tag_name: ${{ github.ref }}
          draft: true
          preset: angular # Use conventional-changelog preset
